import type { ChatMessage } from "./messages";

// POST /forge/idea — body shape.
export interface ForgeIdeaRequest {
  message: string;
  history: ChatMessage[];
  // Stable per-chat ID generated by the client. Stateful providers (Claude Code SDK)
  // use this to track session continuity; stateless providers ignore it.
  conversationId: string;
}

// SSE event stream from POST /forge/idea.
// Each event is a JSON-encoded payload in an SSE `data:` line.
export type ForgeIdeaEvent =
  | { type: "token"; text: string }
  | { type: "done" }
  | { type: "error"; message: string };
